exclude: ['scss/*', 'config.rb', 's3_website.yml', 'config.yml', 'vendor', 'Gemfile', 'Gemfile.lock', 'circle.yml', '*.sh']
markdown: rdiscount
highlighter: pygments
permalink: /:title/
name: Liu's Log
url: 'https://chunweiliu.github.io'
description: The Blog of Chun-Wei Liu, Engineer in San Francisco
tagline: Software and Something Else
author: Chun-Wei Liu
twitter: chunweiliu
copyright: All rights reserved. 
rss_path: /
rss_name: rss.xml
assets:
  dirname: assets
  baseurl: /assets/
  css_compressor: yui
  js_compressor: yui
  cachebust: hard
  cache: false
  debug: true
  gzip: nil # Cloudflare will do this
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
